[package]
name = "untitled"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
show-image = "0.10.1"
rand = "0.8.4"
priority-queue = "1.2.1"